[workspace]
resolver = "2"
members = [
	# "Foundation" libraries. These basically are used
	# by the rest of the letsplay repo to do certain things.
	"crates/letsplay_core",
	"crates/letsplay_gpu",
	"crates/letsplay_av_ffmpeg",

	# Libretro frontend library
	"crates/letsplay_retro_frontend",
	"crates/retrodemo",

	# Runner libraries
	"crates/letsplay_runner_core",
	"crates/letsplay_runner_retro",

	"crates/letsplayd"
]

# Default package fields. We forbid publishing by default
# since a lot of the crates we build here aren't really useful
# outside of the Let's Play codebase, however some are.
[workspace.package]
publish = false
version = "0.1.0-alpha0"
edition = "2021"


[workspace.dependencies]
anyhow = "1.0.86"

libc = "0.2.155"
libloading = "0.8.5"

clap = { version = "4.5.6", features = ["cargo"] }

tokio = { version = "1.37.0", features = [ "full" ] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
thiserror = "2.0.11"

gl = "0.14.0"
gl_generator = "0.14.0"

# protobuf
protobuf = { version = "4.30.0-beta1" }
protobuf-codegen = { version = "4.30.0-beta1" }

# NVIDIA
cudarc = { version = "0.13.3", features = [ "cuda-11050" ] }

[patch.crates-io]
ffmpeg = { version = "7.1.0", package = "ffmpeg-next", git = "https://github.com/hgaiser/rust-ffmpeg", branch = "codec-context-settable" }
ffmpeg-sys-next = { version = "7.1.0", git = "https://github.com/hgaiser/rust-ffmpeg-sys", branch = "cuda" }
