[package]
name = "letsplay_runner_core"
# TODO: Once this is working, we might actually *want* to
# release this as public so other people can write runners
# without having them need to be in the Let's Play codebase.
# For now, however, leaving it unpublished is a good move.
publish.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true

bytes.workspace = true

clap.workspace = true

tokio.workspace = true
tokio-util = { workspace = true, features = ["codec"] }
futures-util = { workspace = true, features = [ "sink" ] }
futures.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

#protobuf.workspace = true

serde.workspace = true
serde_json.workspace = true

# GPU
letsplay_core.path = "../letsplay_core"
letsplay_gpu.path = "../letsplay_gpu"
gl.workspace = true

# AV stuff
letsplay_av_ffmpeg = { path = "../letsplay_av_ffmpeg", default-features = false }
cudarc = { workspace = true, optional = true }



[build-dependencies]
#protobuf-codegen.workspace = true

[features]
# Default to compiling in all possible HW support
default = [ "av-nvidia" ]

# Enable NVIDIA support 
av-nvidia = [ "letsplay_av_ffmpeg/nvidia", "dep:cudarc" ]

# Build runner client code. 
client = [ ]

# Build runner server code
server = [ ]

# bleh
temp = []
