[package]
name = "retrodemo"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
minifb = "0.27.0"
retro_frontend = { path = "../retro_frontend" }

tracing = "0.1.40"
tracing-subscriber = "0.3.18"
