[package]
name = "letsplay_runner_retro"
publish.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
# Let's Play-specific dependencies
letsplay_core.path = "../letsplay_core"
letsplay_runner_core.path = "../letsplay_runner_core"

# Stuff we want
tracing.workspace = true
anyhow.workspace = true
