[letsplay]

# The listen address and port to use for QUIC
listen_address = "0.0.0.0"
listen_port = 5309

local_runner_datadir = "./data"

# define local runners
[local_runners]
runner1 = { type = "retro", core = "cores/swanstation_libretro.so", rom = "roms/game.bin" }
