[letsplay]

# The listen address and port to use.
listen-address = "0.0.0.0"
listen-port = 5309

# Filesystem location for RetroArch cores
cores-location = "./cores"

# Filesystem location for ROMs
rom-location = "./rom"

# TODO: much more!