// This .proto contains definitions that are used for communication between
// letsplayd and a runner process.
//
// These are the messages that are sent to a RPC server.
edition = "2023";

// A message sent to letsplayd.
message ClientMessage {
	message Hello {
		// A standardized type id, like:
		// 'letsplay.libretro'
		//
		// Note that only runners part of the Let's Play repository should
		// use 'letsplay.' IDs. External ones should use an alternate one.
		string typeid = 1;

		// Returns the runner API version.
		// This is incremented on any incompatible bump to
		// letsplay_runner_core's protobufs.
		//
		// The current one is '0'.
		// Previously: (past version, date it was discontinued, reason why)
		fixed32 version = 2;

		// The emulator ID this runner is for.
		// Duplicate IDs are not allowed.
		string emu_id = 3;
	}

	// Provides a new video frame for a runner server 
	// to broadcast to its connected clients.
	message VideoFrame {
		// The type.
		enum FrameType {
			// A key frame.
			KEY = 0;

			// A intra frame. Requires a previous KEY frame and (any) previous
			// INTRA frames to have been decoded beforehand.
			INTRA = 1;
		}

		// The type of this frame
		FrameType frame_type = 1;

		// A H.264 NAL Unit packet for the video frame.
		bytes data = 2;
	}


	// Provides a new audio frame for a runner server 
	// to broadcast to its connected clients.
	message AudioFrame {
		// Opus encoded audio packet.
		bytes data = 1;
	}
	

	oneof Oneof {
		Hello hello = 1;

		VideoFrame video_frame = 5;
		AudioFrame audio_frame = 6;
	}
}
