[package]
name = "letsplayd"
version = "0.1.0"
edition = "2021"

[dependencies]
# for now; we can slim down later
tokio = { version = "1.37.0", features = [ "full" ] }
toml_edit = "0.22.13"

retro_frontend = { path = "../retro_frontend" }

tracing = "0.1.40"
tracing-subscriber = "0.3.18"
