[package]
name = "letsplayd"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { workspace = true }
toml = "0.8.19"

retro_frontend = { path = "../retro_frontend" }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
