[package]
name = "letsplay_gpu"
description = "EGL bindings for Let's Play"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
gl = "0.14.0"

[build-dependencies]
gl_generator = "0.14.0"
