[package]
name = "letsplay_av_ffmpeg"
description = "FFmpeg abstraction for Let's Play"
# TODO: Need to publish if we publish letsplay_runner_core.
publish.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true

letsplay_core.path = "../letsplay_core"

# GPU stuff
letsplay_gpu.path = "../letsplay_gpu"
gl.workspace = true

ffmpeg = { version = "7.1.0", package = "ffmpeg-next" }

# CUDA (NVIDIA-specific) deps
cudarc = { workspace = true, optional = true }
libloading = { workspace = true, optional = true }

tracing.workspace = true

[features]
# Nvidia hardware-specific support
nvidia = [ "dep:cudarc", "dep:libloading" ]

# Benchmarking.
benchmark = []
