[package]
name = "letsplay_av_ffmpeg"
description = "FFmpeg abstraction for Let's Play"
publish.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true

letsplay_core.path = "../letsplay_core"

# GPU stuff
letsplay_gpu.path = "../letsplay_gpu"
gl.workspace = true

cudarc = { version = "0.12.1", features = [ "cuda-11050" ] }
ffmpeg = { version = "7.1.0", package = "ffmpeg-next" }
libloading = "0.8.5"

tracing.workspace = true

# FIXME: Features or such so we can abstract given HW implementations.

