[package]
name = "retro_frontend"
version = "0.1.0"
edition = "2021"
# Could be useful, and does build seperately, so...
# publish = false

[dependencies]
libc = "0.2.155"
libloading = "0.8.3"
libretro-sys = "0.1.1"
once_cell = "1.19.0"
rgb565 = "0.1.3"
thiserror = "1.0.61"
tracing = "0.1.40"
